name:                polysemy-acquire
version:             0.0.0.1
github:              "googleson78/polysemy-acquire"
license:             BSD3
author:              "Georgi Lyubenov"
maintainer:          "godzbanebane@gmail.com"
copyright:           "2021 Georgi Lyubenov"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/polysemy-acquire#readme>

dependencies:
- base >= 4.7 && < 5
- resourcet
- polysemy
- polysemy-plugin

ghc-options:
- -Wall
- -fplugin=Polysemy.Plugin

library:
  source-dirs: src

tests:
  polysemy-acquire-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - polysemy-acquire
    - hspec
